### ISSUE TITLE
Add Dark Reader lock

### ISSUE THREAD

**Issue by bershanskiy** [lerndmina/lerndmina.dev#6]
This is an alternative solution to https://github.com/darkreader/darkreader/pull/11177

Please add a [Dark Reader lock as described here](https://github.com/darkreader/darkreader/blob/main/CONTRIBUTING.md#disabling-dark-reader-on-your-site) by adding the following HTML to the page:
```html
<head>
    <meta name="darkreader-lock">
</head>
```

**Comment by lerndmina** [comment]
Thanks for this, I somehow managed to skip over it when reading [CONTRIBUTING.md](https://github.com/darkreader/darkreader/blob/main/CONTRIBUTING.md). This is now fixed in https://github.com/lerndmina/lerndmina.dev/commit/0df3bb366c15e15a6057825190f83ffb20c2c8df :)
